.github/ISSUE_TEMPLATE/pull_request_template-yml.md, .github/ISSUE_TEMPLATE/pull_request_template.md, README.md
added the necessary changes from the resource given by the mentor
=> #15  added README file  for local running of the application 

roles.html, src/css/roles.css
1. Icons: Added icons in front of the button for improved visual appeal and usability.
2. Gradient Animation: Implemented a gradient animation effect that activates on hover, enhancing the button's interactivity.
3. Description: Included a descriptive text below the button to provide context and enhance user experience.
Fixes #24: Adding icons to the button.
Fixes #25: Implementing gradient animation on hover.
Fixes #27: Adding a description below the button.
1. Fixes #24: Adding icons to the button.
2. Fixes #25: Implementing gradient animation on hover.
3. Fixes #27: Adding a description below the button.
=> Enhance Button with Icons, Gradient Animation, and Description

.gitignore, package.json
I have added the .gitignore file and initialized the npm . Please label it as hactoberfest-accepted.
=> fixes - #34 added .gitignore and initialized npm

src/css/user-map.css, src/css/user.css, user-map.html, user.html
Modified the user & user-map webpages to ask user's location and search the hospitals from the list
✅ Closes: #20
This pull request includes several updates to the styling and functionality of the user interface for displaying hospital locations and lists. The key changes involve enhancing the user experience with improved styles and geolocation features.
* [`src/css/user-map.css`](diffhunk://#diff-56f29d1ccce9d6761fcf27ce454f416fe50e4a24fdab093d0784dd8b6f1373e3R13-R26): Added background color, border-radius, and box-shadow to `body` and `#map` elements to improve the visual presentation. Also added a transition effect to buttons. [[1]](diffhunk://#diff-56f29d1ccce9d6761fcf27ce454f416fe50e4a24fdab093d0784dd8b6f1373e3R13-R26) [[2]](diffhunk://#diff-56f29d1ccce9d6761fcf27ce454f416fe50e4a24fd …
=> fix: 🐛 Display Nearby Hospitals

hospital.html
Added Logo and Tagline to the First Page
=> Dashboard Updated

.github/ISSUE_TEMPLATE/bug-report.yml, .github/ISSUE_TEMPLATE/feature_request.yml
Please review and inform me for any changes.
=> New pull request

hospital.html, manage.html, src/css/hospital.css, src/css/manage.css
This pull request includes significant updates to the `hospital.html` and the addition of `manage.html` to enhance the hospital management system's user interface and functionality. The most important changes include restructuring the navigation, adding dynamic content sections for drivers and ambulances, and implementing a new management page for adding and editing drivers and ambulances.
* **Navigation Bar and Layout Changes:**
- Replaced the static action buttons with a navigation bar and restructured the HTML layout for better organization. (`hospital.html`)
* **Dynamic Content Sections:**
- Added dynamic sections for displaying driver and ambulance statuses, including placeholders for dynamically injected rows. (`hospital.html`) …
=> Fix Issue #21

README.md
=> Added Description for this repo

login.html, src/css/login.css, up.html
I have added a functional password eye button which toggles the input password visibility. Attaching a screen recording below.
https://github.com/user-attachments/assets/f907d5b5-6e68-4395-b024-948d5d345b9c
=> added password eye button

roles.html, src/css/roles.css
**This pull request adds a new header section to the application, including a logo that enhances branding and improves the user interface. The header is designed to be responsive and user-friendly**.
**Added a header component with a logo.
Updated CSS styles for the header.
Adjusted layout for responsiveness.**
=> Add Header Section and Logo

src/css/roles.css
- Fixes #65 
- Alignment set of users
- User specific area set
- Used a light background color to highlight those sections.
- That unnecessary hover effect removed.
- Added some padding to improve the UI.
- Darken the icon background color.
=> [FIX] Roles and FAQs style changes

hospital.html
This pull request addresses the issue of the logo being aligned to the left. The fix involves updating the CSS to center the logo within the header or navigation bar. I ensured that the logo remains properly centered across different screen sizes, improving the visual balance and making the layout cleaner and more user-friendly.
=> Fix: Centered the logo

login.html, up.html
Removed this unnecessary password strength check for login page 
Now it looks something like this 
And modified the signup page with good password styling and background
This is how it looks for a password with medium strength and green for good strength
=> Removed the password strength in login and added it to sign up with styling

manage.html
Resolved: now it will display that existing drivers is exists.
=> Updated to show existing driver

hospital.html
Project Contribution: Clickable Button for Driver or Ambulance Service
As part of my contribution to the project under GSSOC, I developed a clickable button feature for driver or ambulance services. This feature is designed to streamline emergency response by allowing users to directly request assistance from a driver or ambulance with a single click. By simplifying the interaction and making it more user-friendly, this enhancement improves the overall efficiency of emergency resolutions.
Key Contributions:
Implemented a user-friendly clickable button to connect users with emergency services (driver/ambulance) directly.
Enhanced responsiveness and accessibility for quick action in time-sensitive situations.
Collaborated with the project team to integrate the feature seamlessly into the …
=> Make Clickable Driver or Ambulance button

login.html, src/css/login.css
Responsiveness : 
UI:
Corrected the Login Page UI and made it simple and sobber 
Changes are made in files
1. login.html 
2. login.css
=> Remade Login UI with HTML & CSS

manage.html, script.js
Reverts mansiruhil13/Bobble-AI#113
=> Revert "Fix: Enable functionality for "Manage Driver" and "Manage Ambulance" buttons"

login.html, src/css/login.css
=> Fixed Login UI #104

login.html, src/css/login.css
Reverts mansiruhil13/Bobble-AI#122
=> Revert "Fixed Login UI #104"

index.html
Someone had changed the landing page too, i have also fixed that
=> Fixed landing page #104

index.html
Reverts mansiruhil13/Bobble-AI#124
=> Revert "Fixed landing page #104"

index.html
Reverts mansiruhil13/Bobble-AI#128
The homepage is messed up.. revert this PR to resolve.
Check Linkedin @mansiruhil13
=> Revert "Revert "Fixed landing page #104""

index.html
=> [FIX] Fixing homepage and Deploy

src/css/login.css, src/css/roles.css
=> making the header section stickey

src/css/login.css, src/css/roles.css
Reverts mansiruhil13/Bobble-AI#135
=> Revert "making the header section stickey"

.github/workflows/jekyll-gh-pages.yml
Reverts mansiruhil13/Bobble-AI#143
=> Revert "fix: 🐛 Removed the Manual Github pages Build & deploy action"

user-map.html
This pull request introduces a new search bar feature within the user map interface, enhancing the user experience by allowing users to quickly find specific locations or resources.
=>  Add Search Bar Feature to User Map

contact.html
changed the contact section completely 
in the left hand side is displays the essential contact details also in the right hand side their is a form screen that has various field.
The map section is just below the the contact us section giving it a modern and minimal look.
=> changed the contact page

contact.html, features.html, home.html, team.html
modified below files:-
contact.html
team.html
home.html
features.html
Changed Ambulance Monitoring System to Ambulance Tracking System in above files
"Tracking" word is better in our project ,that tells our project functionality more
=> Changed "Ambulance Monitoring System" to "Ambulance Tracking System"

ambtracker.html, src/css/driver.css, src/css/hospital.css, src/css/index.css, src/css/login.css, src/css/roles.css, src/css/up.css, src/css/user-map.css, src/css/user.css
This pull request introduces a fully customized scrollbar that aligns with the website's theme, providing a more polished and uniform user experience.
**Before:**
The scrollbar's default, unstyled appearance didn’t align with the website's overall design, resulting in a lack of visual cohesion.
**After:**
- The scrollbar has been customized to a consistent width and style, matching the website's theme. This provides a uniform and sleek design that blends seamlessly with the content.
Thank you for reviewing my pull request!
=> ScrollBar Customization

login.html
in login page ,sign up option is not working 
so, 
i added signup page and refered its link in login page
https://github.com/user-attachments/assets/82526528-8f1f-4ddc-839c-d35d5b38dac9
=> added signup page in login page,backlink

about.html
about.html page is missing
so i created a about.html page and added some basic content of our project 
level 3 please 
i will add more content in about.html soon
=> created a basic about.html page

contact.html, features.html, index.html, login.html, team.html
https://github.com/user-attachments/assets/bd524c55-c88b-4ebd-b197-3d5c14b574e1
=> Fixed HomePage route issue #178

contact.html, features.html, index.html, team.html
#182 Resolved
I have successfully updated the Twitter-X icon
Refer to the below image for the changes I made :
@mansiruhil13 Please review it.
Thank you
=> Update twitter-x icon

contact.html
#192 Resolved
Updated footer 📸 
@mansiruhil13 
Please review it. 
Thank you
=> Updated footer

contact.html, features.html, index.html, team.html
Hey, i finished adding the icons to the header. I have made sure that all four index, features, contact and team files have been changed successfully. 
Issue number #191 
Hope you like it 🙏
Please label me under gssoc and hacktober
=> Icons Added | #191

index.html
=> [FIX] Landing page fixed and links are working

about.html
Proposed Fix:
Add a Description: You can include a brief description about the project and its importance in the 'About' section.
Enhance the content: Provide a clearer message, so it reflects the mission and vision.
Make sure the language is concise and easy to understand.
=> Update Documentation section

index.html
quick links in footer section fixed
=> fix footer section

index.html, src/css/index.css
=> [FIX] Footer bug fix

index.html, src/css/index.css
=> [FIX] Brand name added and responsiveness added

login.html, login.js, src/css/login.css
Updated the login page by enhancing the HTML structure for accessibility and responsiveness, redesigning CSS for a modern look, and adding a `login.js` file for input validation and user interaction. These changes improve usability and provide a better overall user experience on both desktop and mobile devices.
=> login UI/UX

index.html
**Description:**
This pull request introduces an enhanced logo animation and styling feature for the Ambulance Monitoring System. The updates include:
1. **Sliding Animation:** The logo now slides in from the left side upon page load, creating a visually engaging introduction.
2. **Letter Animation:** Each letter of "Ambu" drops in sequentially, adding a playful touch to the branding.
3. **Color Change:** The "Ambu" part of the logo is styled in red, making it stand out and reinforcing brand identity.
4. **Improved User Experience:** The new animations improve user engagement and navigation experience on the website.
**Screen Recording**
https://github.com/user-attachments/assets/49c27f6a-4227-4a40-af46-f84f037c2807
**Issue no. :** #238
=> Enhance Logo Animation and Styling

about.html, ambtracker.html, contact.html, driver.html, features.html, homepage.html, hospital.html, index.html, login.html, manage.html, roles.html, team.html, up.html, user-map.html, user.html
`Successfully adding a favicon to your website enhances its branding and user experience.`
<h3> FEVICON :</h3>
=> Added fevicon icon in all HTML Files

index.html
#203
https://github.com/user-attachments/assets/6945e635-755b-455f-bf8d-0a9a2e9fb8d4
=> display confirmation message after submitting newsletter form

contact.html, features.html, index.html, src/css/index.css, team.html
**********************************Before changes*****************************************
*******************************************************After changes***************************************
Hi @mansiruhil13,
Title: "Revamping the Navbar: Contributing to an Open-Source Project for a Sleek and Modern Design" #161.
issue:#161.
I recently updated the navbar, font family, and logo across all website pages for your project to make it more attractive and user-friendly. I've attached screenshots of the changes and would love to share a comparison between the original and the updated design. You can see the previous look and the current website version, which is now live online.
Best regards,
@khurshed07
GitHub: https://github.com/khurshed07
=> modify navbar and font family khurshed07

about.html, team.html
Fixed the triple footer on team.html page
=> fixed triple footer team.html

index.html
Fixed the footer 
Assign me this under gssoc-ext  level 3
Before 
After
=> fixed footer 

index.html, script.js, src/css/index.css
#258
https://github.com/user-attachments/assets/3113b2e5-5031-4322-b28e-988c26bcc708
=> pre loader

index.html
Clicking Home on index.html lead will now lead back to home page itself and wont show error.
=> Solve Bug #276

index.html, src/css/index.css, team.html
fixes #193 
before:
after:
https://github.com/user-attachments/assets/3128f2f2-fb2b-4d36-a14a-ef6a27ce6afa
=> Enhance homepage sections

login.html
Changes I make #270 :-
1. Add new Google icon.
2. Add some space between icon.
@mansiruhil13
=> Change icon in signup page

team.html
I corrected the footer in Team Page.
Regarding Issue no. #260 
Screenshot:
=> corrected copyright and footer background of team page

index.html, script.js
This PR introduces a newsletter subscription form that allows users to enter their email addresses and displays a confirmation message upon successful submission. Additionally, it enhances the accordion component, enabling users to expand and collapse sections while ensuring only one section is open at a time. Visual indicators have been added to enhance the user experience. Future updates will connect the form to a backend service for actual email handling.
=> Confirmation message after submitting newsletter form

index.html, src/css/index.css, src/css/login.css
the home page is working @mansiruhil13
=> Issue #291 solved

index.html
issue #311
the logo refresh issue is now fixed.
=> fixed the issue of logo redirection 

index.html, src/css/common.css, src/css/driver.css, src/css/hospital.css, src/css/index.css, src/css/main.css, src/css/roles.css, src/css/up.css, src/css/user-map.css, src/css/user.css
New font style: Poppins, sans serif
@mansiruhil13 Assign me to this PR, add labels with level.
Reveiw it and merge my PR.
Thank you
=> Implement new font style

home.html, homepage.html, index.html
Made the footer consistent, where there were multiple "© 2024 AmbuFlow. All rights reserved." to one, and also somewhere it as Ambulance Monitoring System written instead of AmbuFlow so changed that for consistency in footer.
Issue  #282
=> Fixing footer

homepage.html, index.html
https://github.com/user-attachments/assets/8f489697-d00c-40ee-8ce0-955735a9637c
give level 2 if possible
issue  #316
=> Optimised it for mobile or any screen size

Feedback.html, about.html, contact.html, features.html, index.html, team.html
https://github.com/user-attachments/assets/b5be3203-38a7-4bb0-9d09-fdc3abce6e07
Added feedback option #272
=> added feedback option

index.html, src/css/index.css
=> [FEAT] FAQ Section Added

login.html, src/css/login.css, src/css/up.css, up.html
I have successfully addressed the issue where the "Get Started" button on the home page was redirecting to the old sign-up page. It now correctly links to the new sign-up page. Additionally, I have made several enhancements:
- Changed the color of the home button and added hover effects for improved interactivity.
- Redesigned and resized the social media icons for a more polished appearance.
- Added a "locker" button in the password section to toggle visibility, which is now functioning perfectly.
Please review these changes and accept my pull request if it resolves the issue.
Thank you!!
https://github.com/user-attachments/assets/70def655-e897-4e05-a6ab-f5fcae2195e5
=> Fixed issue with 'Get Started' button redirect and enhanced the home button, social media icons, and password locker button.

home.html, style.css
made it easy for the ppl who wantes to contribute to the project as the whole css as in html it would be confusing and hard to debug  and also plz upgrade the level
=> made it responsive and also created style.css for better usage for p…l who contribute

src/css/user.css
=> updating user css

Feedback.html
=> [FIX] Feedback section fixed

Feedback.html, index.html, team.html
this is consistent through out the pages. @mansiruhil13 can you assign this
=> fixed navbar and footer

features.html, home.html, homepage.html, hospital.html, index.html, manage.html, roles.html, src/css/manage.css, team.html
_**ISSUE NO: #340**_  has been fixed.
---> Now clicking on Home in Navbar while in Home page leads to Home Page and does not give a 404 Error
---> Clicking on Logo Icons also lead to Home Page
=> [Bug Fixed] Nav-Bar Home icon Bug has been fixed

Feedback.html, contact.html, features.html, homepage.html, index.html, team.html
Issue #371 resolved
@mansiruhil13 
I have enhanced footers on all the pages, try giving level 3
Review it, assign me to this PR, and add labels.
Thank you
=> Enhance footer

Feedback.html, contact.html, features.html, index.html, login.html, src/css/login.css, src/css/up.css, team.html, up.html
issue number:#177 has been fixed
I contributed to the development of the website by implementing a dynamic mouse cursor trail effect using JavaScript and CSS. 
This feature enhances the user interface by creating a visually engaging experience as the cursor moves across the screen, improving user interaction and overall website aesthetics.
Thank You!!
https://github.com/user-attachments/assets/3df96921-87c2-4d22-910f-c2b72ece8184
=> Implementation of Dynamic Mouse Cursor Trail Effect

index.html, src/css/index.css
Fixed the homepage
#382 resolved
=> Home page fix

features.html, index.html, script.js, team.html
**Issue Description:**
The subscription form in the footer section was not displaying the "Thank You" message properly upon submission, and the page was refreshing unexpectedly.
**Changes Made:**
Fixed form submission behavior: The form no longer refreshes the page upon submission.
Added "Thank You" message display: A "Thank You for subscribing!" message is now shown correctly after the form is submitted.
Repositioned the JavaScript: Moved the form handling script to the bottom of the HTML file before the </body> tag for better functionality.
**Issue solved:-** #252 
**proof of concept:-**
https://github.com/user-attachments/assets/e7e47b45-0734-46f0-a213-c8e98b9bf1e9
@mansiruhil13
=> Footer Subscription Form Updates

index.html
Now the navbar is fixed on the total scroll and also when the logo is clicked the page returns to main home page
Solves : #396
=> Made enhancement to navbar behavior

index.html
=> Fixed "Newletter issue" #398

index.html
=> Fixed navbar and buttons on navbar

team.html
=> [FIX] Team Page Fixed

index.html
- Fixes #406 
https://github.com/user-attachments/assets/43850747-db23-4c40-805d-b1ae93e0ccce
=> [FIX] Ugly Hover Effect on Footer Removed

index.html
=> Added favicon link in index.html

contact.html
styling of icons is not according to theme color an styled properly.
before styling:
https://github.com/user-attachments/assets/fb8db6db-530e-4cc2-a311-e089441361c6
After styling:
https://github.com/user-attachments/assets/982be144-38f6-4052-ae4a-a9d27dd75650
=> styling of icons in contact page

terms.html
I have added the file of Terms of Services and also updated the UI of Terms of Services page.
=> This PR is related to the issue no. #$453.Files terms.html has been added

contact.html, index.html
Hello PR,
Fixed issue number - #419
@mansiruhil13
=> Fixed icon image border issue ! #419

Feedback.html, contact.html, features.html, index.html, login.html, up.html
issues #394 [SOLVED}
- Added a blue cursor tail effector to enhance visual feedback and interactivity for users.
- Limited the cursor effect to the home page, maintaining a playful and engaging feel for first-time visitors.
- Ensured that other sections of the site, such as the profile page, retain a professional and clean look.
- This update strikes a balance between a dynamic user experience and a polished, formal design for the rest of the site.
https://github.com/user-attachments/assets/c20f0ffa-7f5f-4813-8610-ab2b4df162f4
=> Add Blue Cursor Tail Effector and Limit to Home Page for Improved UX

about.html, index.html
Issue #437  and all double footer and header so merge this asap so there will be no error afterward, this must be level 3 
Fixed
Fixed 
Fixed
=> Fixed About Page Home and Removed Doble headers and footers 

features.html
Closes #441 
Added Driver Performance Monitoring in features.
=> Added Driver Performance Monitoring

index.html
The PR fixes issue #475 .
Previously the navbar just stayed at the top of the page and disappeared when scrolled down, so i made it hover at the top of the page (fixed it's position). After reviewing the code i found out the navbar was supposed to hover but due to a bug it wasn't working as intended!
Here's the change after the bug fix:
don't forget to label it as GSSOC extd, hacktoberfest accepted with level1/2/3 accordingly.
Thank You!
=> FIXES ISSUE #475: [Feature Request]: The Navbar hover above page feature.

homepage.html
This pull request introduces hover effects to both the .team-feature and .contact-feature classes, enhancing the user interface. The hover effect improves visual feedback and encourages user interaction, making the components more engaging.
These changes elevate the overall user experience and align with modern web design practices.
**Request**: I believe these enhancements will significantly benefit our users. Please consider merging!
Fixes: #488 
Thank you!
=> Add Hover Effects to Team and Contact Features

index.html, nearby.html, style.css
Implement a "Nearby Hospital" feature that allows users to access a map of nearby hospitals based on their current location. This feature will enhance the emergency response process by enabling users to quickly find and navigate to the nearest healthcare facilities.
1. A user requests an ambulance and, after confirmation, can view nearby hospitals on a map.
2. The user sees the nearest hospitals, their distances, and additional information to make informed decisions while waiting for the ambulance.
1. Enhanced User Experience: Empowers users with immediate access to hospitals during emergencies.
2. Faster Decision Making: Users can choose the closest hospital based on distance and services.
3. Increased Safety: Saves valuable time, potentially saving lives with timely medical attention. …
=>  Feature Enhancement: Nearby Hospital Map Integration

features.html
- Fixes #446 
!! Nav not found
=> [FIX] Feature Page - Double Grid Solved

Contactus.html, team.html
Solved issue by adding contact us form.
=> issue solved by adding contact us form

sitemap.html, terms.html
I have added the sitemap.html file so now all the urls of pages are working correctly.
=> This PR is related to issue#459. Sitemap.html has been added

contact.html, index.html, src/css/index.css, style1.css, team.html
Hello PR,
Fixed issue number - #471
https://github.com/user-attachments/assets/0c64d5cb-646c-49f4-bd18-5711f268f3a3
https://github.com/user-attachments/assets/2b5ee7b5-41d0-4914-aa02-ca789d5053e0
https://github.com/user-attachments/assets/0e9a7751-6d14-49b2-a5af-5dd126602512
& I also fixed this issue in "Team" page !
Issue -
https://github.com/user-attachments/assets/15e9ca4a-f5ab-42c0-87d8-2717abb3ec77
Issue Fixed !
https://github.com/user-attachments/assets/3eceed63-fcf9-4e00-a549-7623002263fa
@mansiruhil13
=> Fixed the icon boxes issue ! #471

Feedback.html, contact.html, features.html, hospital.html, index.html, login.html, preloader.js, preloaderStyle.css, team.html, up.html
Fixed issue: #452 
Styling has been applied to the preloader . The preloader is present on all pages of the website with styling. 
*Improvements:*
1. *Optimized Preloader:* Enhanced the preloader animation on the Feedback, contact, features, index, login, team, and up pages to improve user experience.
2. *Revamped Preloader Design:* Redesigned the preloader with modern CSS styling to enhance visual appeal.
3. *Dedicated Preloader Script and StyleSheet:* Created a separate JavaScript file named `"preloader.js"` to manage the preloader functionality and CSS file named `" preloaderStyle.css"` to enhance the styling and functionality, ensuring better code organization and maintainability.
The program was tested locally on a machine using the Chrome browser. To verify the changes, the website …
=> Improve preloader

homepage.html, style1.css
i think i solved issue. Quick links part
=> change in  footer section

contact.html
=> [FIX] Contact Page Nav Bar Added

team.html
#632 Resolved
@mansiruhil13 
Review it, thank you.
=> Remove duplicate items

.github/workflows/static.yml, CODE_OF_CONDUCT.md
updated code of conduct to version 2.1
level2
=> changed code of conduct to version 2.1

contact.html
I have added the map with the location that is given in the contact section of the website .
Now the user can get your location direct from there .
Also,
Embedding Google Maps enhances **local SEO** improving your visibility in search results for potential customers searching for services in our area.
=> Added google map

robots.txt
added robots.txt 
this PR fixes #683 issue
=> added robots.txt

contact.html
=> [FIX] Double contact us icons removed

Feedback.html, contact.html, features.html, index.html, team.html
**Title:** Enable Dark Mode Toggle Button and Add to Relevant Pages
**Related Issue:** #701
This pull request implements a dark mode toggle button, allowing users to switch between light and dark themes seamlessly. The toggle has been added to all relevant pages, enhancing user experience and accessibility.
- Added a dark mode toggle button in the navigation/header section.
- Updated styles to support both light and dark themes.
- Ensured compatibility across all relevant pages, including:
- Home
- Features
- Contact
- team
- feedback
- Tested the toggle functionality on various devices and browsers.
- Verified that the dark mode persists across page refreshes.
- [https://drive.google.com/file/d/159waVwBQtSaEVC_xw6JleKzM-hkB6OrT/view?usp=sharing](https://drive.google.com/file/d/159waVwBQtS …
=> Enabling Dark Mode Toggle Button and adding it on every relative page… #701

about.html
footer added at about us and also margin settled for about us section from top and bottom
Accept this PR .
=> footer added at about us and also margin settled for about us section from top and bottom

index.html
Before version can be seen in issue
**Changes made**: 
- change color on hover
- button rotate 180 deg with smooth transition - no jerk now
- smooth transition while opening and closing faq.
https://github.com/user-attachments/assets/4b42f0fa-0b1e-4c16-9694-73a2db5c5626
Additional changes: Also enhanced theme switch button on top right corner.
=> faq smooth transition and animations

Feedback.html, contact.html, features.html, index.html, team.html
=> added language translator 

index.html
=> Update index.html FAQ color to black 

Feedback.html
Fixed hover issue in feedback page in footer section.
=> Fixed hover issue in feedback page in footer section.

Contactus.html, Feedback.html, contact.html, features.html, team.html
Hey @mansiruhil13 as you assigned me task #(715) I have completed that , that is linked of logo with home page. Kindly merge this pull request.
=> Logo linked with home page

Contactus.html, Feedback.html, chatbot.html, contact.html, driver.html, features.html, homepage.html, hospital.html, index.html, login.html, nearby.html, privacy.html
Update the css properties such as transition, font size, font weight, color, opacity, and many more to make website more user friendly.
Issue no : #702 
Thank you for the support
Thank you @mansiruhil13 
Please review the pull request and label it
=> I had made the modification

Feedback.html, contact.html, features.html, index.html, login.html, nearby.html, team.html, up.html
ADDED THE TRANSLATOR TO EVERY PAGE 
ISSUE  #710
PLEASE GIVE LEVEL 2
https://github.com/user-attachments/assets/3aac05e5-9ce1-44c8-9f8b-8ad7cecda6e1
=> ADDED THE TRANSLATOR

team.html
solved the problem #723 
all unwanted links has been removed
=> deleted unwanted links in team page

index.html, style1.css
- Fixes #771 
https://github.com/user-attachments/assets/ed40ce36-b6d3-4c67-8866-b4d58415a394
=> [FIX] FAQ footer alignment solved

Feedback.html
solved issue #726 
i removed the unwanted text present on the bottom of the feedback page, also changed the java script code as it show me 9+ error in it. also i added the backtotop button in it and make it functional
=> removed the unwanted text on feedback page,

team.html
Hello, PR
Fixed issue number - #610
https://github.com/user-attachments/assets/c6a98bcd-35ff-410f-91fb-f08140a0919d
=> Fixed double icon box issue in Team page ! #610

index.html
=> footer of this website not completely responsive and Aline content accurately

index.html
@mansiruhil13 This is issue no. #661 .
I have made the necessary changes here. 
Added three new frequently asked questions (FAQs) to the ambulance monitoring system's FAQ section. These questions focus on ambulance cancellation, safety instructions, and handling technical issues related to the tracking system.
=> Added 3 FAQs

features.html
Hello, PR
Fixed Issue - #799
https://github.com/user-attachments/assets/2ff0190c-394e-4d61-be63-468b7a422ec8
https://github.com/user-attachments/assets/94e4535b-84e3-409b-b8b1-2544d0c996dd
=> Fixed Dark & Light mode buttons size issue ! #799

Feedback.html, contact.html, features.html
Hello, PR
Fixed issue number - #798
=> Remove Extra Translate button done ! #798

Contactus.html, Feedback.html, contact.html, features.html, index.html, team.html
Solves Issue #741 
Description:
I have relocated the chatbot button in home page from bottom left to bottom right. Following the same location, i have added chatbot buttons in all webpages.
Output:
I have checked if this feature is causing any issues. All clear!
=> Relocation and addition of chatbot button to all webpages.

Feedback.html, contact.html, features.html, team.html
- Center-aligned the footer text in the mentioned sections for improved aesthetics.
- Ensured the text remains properly centered across different screen sizes and devices.
- Made sure the changes maintain responsiveness without affecting the overall layout structure.
- **Cleaner Layout:** The centered text creates a more organized and professional appearance.
- **Improved User Experience:** A more structured flow of information enhances readability and usability.
- **Consistency:** The footer now has a uniform look across all sections, providing a polished and cohesive design.
- Tested the alignment across various screen sizes to ensure responsive design.
- Verified that the text aligns perfectly in all relevant sections on both mobile and desktop views.
=> fix the footer in center in all sections.

src/css/up.css, up.html
=> home button visible

Feedback.html, contact.html, features.html, team.html
Hello, PR
Fixed issue number - #844
Issue Fixed -
https://github.com/user-attachments/assets/66fb6b2a-20b4-49bd-abf3-e5f1bcc75100
=> Fixed website logo animation issue ! #844

Backend/Controllers/ambulanceController.js, Backend/Models/Ambulance.js, Backend/Models/User.js, Backend/server.js
fixes #797 
This PR successfully adds ambulance bookings by a user , fetching all ambulances for availability, signup of a user and also creating ambulances to keep the data in the database.
Creating a record for ambulance :
Fetching all ambulances to see availability:
Improved signup for a user
Booking of ambulance by a user
=> Add ambulance APIs

sign_up.js, up.html
[#678](https://github.com/mansiruhil13/Bobble-AI/issues/678)
sign up and sign in issue is solved now when user will sign up then it get a message and login then also get message
=> Sign up and sign in buttons are now in working.

Feedback.html, contact.html, features.html, team.html
Hello, PR
Fixed issue number - #843
Issue Fixed -
=> Fixed Header color issue ! #843

index.html, responsive.css
https://github.com/user-attachments/assets/1e30bb5e-cca5-4f01-bb51-03a3dee8e4f9
I have made the website responsive across devices of various sizes in a css file responsive.css and added a dropdown containing hyperlinks of teams, features, about, etc in the index.html file.
Enhanced the user experience and easyness using the platform. Which is crucial in such type of services.
There is very less deletion of code in any file!
Please do accept my pull request and mark it completed. Thanks!
Regards
Sarang Ahlawat
GSSoC'24 - Ext. Contributor
=> website is now responsive for all size of devices

nearby.html
=> Added search filter at nearby hospitals

.github/PULL_REQUEST_TEMPLATE.md
=> [FIX] Pull Request Preset Update

index.html
=> [FIX] FAQ Section Link Fixed

index.html
---
labels: ''
assignees: ''
---
name: [Bug]: Repetition in FAQ Section #953
This pull requests fixes issue #953 where an answer form the FAQ section was being repeated twice. This pull request made it so that the answer was only displayed once as necessary.
- Fixes #953 
Before:
After:
=> [FIXED] [Bug]: Repetition in FAQ Section #953

index.html
---
labels: ''
assignees: ''
---
I  have added icons to quick links for better user experience please label gssoc ext and hactoberfest accepted level2
@mansiruhil13 
- [ x] New feature (non-breaking change which adds functionality)
- [ x] I have added necessary tests to ensure my changes are effective.
---
=> icons added

Feedback.html
---
labels: ''
assignees: ''
---
Shows thank you message after submitting feedback.
- Fixes #966 
Before
After
---
=> Show thank you message after submitting feedback

Contributing.md, README.md, script.js
---
labels: ''
assignees: ''
---
Update README.md and Contributing.md file
- Fixes #952
- Documentation update
- [ yes ] I have read the contributing document.
-  [ yes ] I have performed a self-review of my own code.
-  [ yes ] I have commented my code, particularly in hard-to-understand areas.
-  [ yes ] I have added necessary tests to ensure my changes are effective.
-  [ yes ] New and existing unit tests pass locally with my changes.
-  [ yes ] Any dependent changes have been merged and published in downstream modules.
=> Update README.md and Contributing.md file

Feedback.html, README.md, index.html, nearby.html
Added the missing Favicons to the Home and Nearby pages and also to the new Feedback page(recently added).
I have updated the banners to fit better in the README file. I have updated the GSSoC banner to GSSoC Extended Program banner and also adjusted the orientation of the Hacktoberfest Banner(a banner is usually landscape and should be more on length that on breadth)
Due to changing your profile picture again the Team Section was broken. I have fixed and adjusted the Team section back to the normal size:
- Fixes #969 
- Before:
It is missing in the **Home page** and the **Nearby page**:
- After:
Home:
Nearby:
Feedback:
- Before:
- After:
- Before:
- After:
---
Please review the PR and assign it to me with the necessary labels.
=> Resolved: Favicon missing on subpage Pages and bugs in README file

index.html
---
about: use this template for the creation of pull requests
labels: ''
assignees: ''
---
- Fixes # 1021
---
=> change the name of the ambuflow to hindi now its looks goods

faq.html
---
labels: ''
assignees: ''
---
faq.html properly worked from about.html page.
- Fixes : #1035 
https://github.com/user-attachments/assets/ca45fa83-1de5-4ac1-bc14-078722243bda
- [X ] I have read the contributing document.
- [ X] I have performed a self-review of my own code.
- [ X] I have commented my code, particularly in hard-to-understand areas.
- [X ] New and existing unit tests pass locally with my changes.
---
=> faq.html routing resolved

user-map.html, user.html
---
labels: ''
assignees: ''
---
- Fixes # (issue)#931
- [... ] Bug fix (non-breaking change which fixes an issue)
---
=> user location is being fetched properly

contact.html
=> Fixed hover issue on contact page of hover issue in quick links and contact info section.

src/css/navbar.css
---
labels: ''
assignees: ''
---
---
=> Added UI functionality to 'Go to Team' and 'Go to Contact' buttons in nav.css file (by miss).

Feedback.html, features.html, src/css/navbar.css, team.html
The navbar designs had broken in features, team and feedback page. Have resolved and followed the same design pattern as home navbar. 
The Nearby option was missing in the feedback navbar, so have added that as well.
- Fixes #732
=> Followed same design of navbar in all webpages and resolved navbar conflicts 

Backend/package-lock.json, team.html
This pull request addresses **Issue #1092** , focusing on enhancing the styles of the buttons in the application. The modifications aim to improve user experience by making the buttons more visually appealing and interactive.
- Increased font size and adjusted padding for better visibility and usability.
- Implemented a flexbox layout in the button container for consistent spacing.
- Added hover effects for the `.login`, and `.get-started`, buttons:
- Background color changes to a darker shade on hover.
- Buttons slightly enlarge when hovered over to provide feedback.
**Before:**
**After:**
1. Pull the changes from this branch.
2. Open the application in your browser.
3. Verify that:
- The buttons display the new styles correctly.
- Hover effects are functional and enhance the user …
=> Enhance Styling of Login and Get Started Buttons

Contactus.html, about.html, faq.html, features.html, home.html
fixed issue #522 
now:
earlier:
now:
earlier:
now :
earlier:
---
=> fixed the inconsistent navigation bar 

SOS.html, about.html, contact.html, features.html, homepage.html, index.html, team.html
---
labels: ''[gssoc-ext](https://github.com/mansiruhil13/Bobble-AI/labels/gssoc-ext)
[hacktoberfest](https://github.com/mansiruhil13/Bobble-AI/labels/hacktoberfest)
[hacktoberfest-accepted](https://github.com/mansiruhil13/Bobble-AI/labels/hacktoberfest-accepted)
[level2](https://github.com/mansiruhil13/Bobble-AI/labels/level2)
assignees: ''adityadhiman0"
---
This pr will add icon in subscription box on all the pages..
---
=> [Fix] Issue #1058 Icon added in subscription box.

login.html, package-lock.json
---
labels: ''
assignees: ''
---
Added code to the login.html to make the sign in page working properly
- Fixes #354
---
=> Updated login.html

faq.html, index.html
---
labels: ''
assignees: ''
---
---
=> improved styling for faq section making it more user attractive

Feedback.html, nearby.html, script.js, team.html
---
name: Dark Mode Button Updated
about: Dark mode button was not working i have fixed that issue.
title: '[FIX] '
labels: ''
assignees: ''
---
name: Dark Mode button
I encountered an issue with the dark mode feature in the project. When I tried to toggle the dark mode using the designated button, it did not work as expected. The page did not switch to the dark mode styling, and the background color remained unchanged.
How it appears before change 
How it appears after change
---
=> [Issue]:Updated Dark Mode Button

index.html, profile.html, testp.css, testp.js
Hello, PR
Add new feature - #1150
Add a normal user profile page and a profile icon in the home page navbar that redirects to the profile page done -
https://github.com/user-attachments/assets/a88f188a-20ec-4189-86b8-c21a49b63234
Page link -
Profile page -
=> Add a User Profiles page done ! #1150

Backend/package-lock.json, index.html
---
title: '[FIX] ' Added links to all the components of footer.
labels: 'gssoc-ext'
assignees: ''@ishakatiyar06
---
- Fixes #1186 
---
=> Added links to the footer section

.github/workflows/auto-label.yml
---
name: Implement Auto-Labeling Workflow for GitHub
about: github workflow added
This workflow will automatically apply specific labels "gssoc-ext" and "hacktoberfest-accepted" to issues and pull requests
- Fixes #1180
=> Implement Auto-Labeling Workflow for GitHub

contributors/contributors.css, contributors/contributors.js
Hello, PR
Improve total contributors page done - #1221
Before - 
🔴This page not display all Contributors, it displays only 30 contributors..
🔴Its value are not dynamically updating in Projects stat section..
🔴It does not display the total Contribution in the project statistics section...
🔴This page is not responsive..
🔴It does not display the total Contributors in the project statistics section..
Now - 
🟢All Issue Fixed properly....
https://github.com/user-attachments/assets/71022739-7ee1-4ba0-ad4a-3864f62563e6
---
=> Improve total contributors page done ! #1221 🟢🟢

index.html
One prominent feature was missing from the grid section . Added that in same format
name:  Updated Grid Section
---
=> Updated grid section

index.html
---
title: 'Resolve language issue of a word "Ambuflow"
labels: ''
assignees: ''
---
- This PR replaces Hindi words with English ones to correct a layout error in the website's content.
- Fixes (#1156 )
- ![Screenshot 2024-11-05 175917](https://github.com/user-attachments/assets/cadf5f56-1d7d-4b49-871c-eca95db60748)
- [ ✔️] Bug fix (non-breaking change which fixes an issue)
- [✔️ ] I have read the contributing document.
- [✔️ ] I have performed a self-review of my own code.
---
=> AmbuFlow name Language changed

contact.html
---
title: '[FIX/Feat] 'Fixed the logo and placeholder  of mail of contact.html page.
labels: ''
assignees: ''
---
- Fixes #1196 
- [] New feature (non-breaking change which adds functionality)
- [] Breaking change (fix or feature that would cause existing functionality to not work as expected)
---
=> Modified contact.html

index.html, signup.css, signup.html
Hello, PR
Add Signup/Register page done - #1223 
https://github.com/user-attachments/assets/206454d0-82b9-450e-bf17-342f1fd5477d
---
=> Add Signup/Register page done ! #1223 🌟🌟

Contactus.html, contact.html
issue - #1207 
-  New feature (non-breaking change which adds functionality)
date
-  I have read the contributing document.
- I have performed a self-review of my own code.
-  I have commented my code, particularly in hard-to-understand areas.
-  I have added necessary tests to ensure my changes are effective.
-  New and existing unit tests pass locally with my changes.
-  Any dependent changes have been merged and published in downstream modules.
=> contact section and contact us section icons colors and animation updated

team.html
issue resolved: #1151
---
labels: ''
assignees: ''
---
- [ x] I have read the contributing document.
- [ x] I have performed a self-review of my own code.
- [ x] I have commented my code, particularly in hard-to-understand areas.
---
=> made team in swipe format

login.html
---
labels: ''
assignees: ''
---
---
=> Made changes to login.html

chatbot.html
issue 🔢 [Bug]: Chat bot html . Send button of Massage bye pressing keyboard Enter button not working .. #1238
Closes: #1238 
---
labels: ''  gssoc-ext 
assignees: ''
---
- Fixes #1238
https://github.com/user-attachments/assets/0c36cf71-664f-4fe5-ac93-ddb75dc964e9
---
=> added enter button key board functinality of chatbot massege send section

index.html
=> Fixed Responsiveness

homepage.html, index.html
The black background color of the footer has been fixed.
=> Fixed the Bug in Footer 

about.html
---
title: '[Feature Request]: i want to redesign about us page #1251 '
labels: ''
assignees: ''
---
- Redesigned the About Us page to improve the user experience and align with the website's overall design aesthetics.
Key changes include:
- Enhanced layout for better readability and visual appeal.
- Improved typography and spacing for a clean and professional look.
- Added responsive design to ensure a seamless experience across devices.
- Incorporated updated content and images to better reflect the brand's identity.
Please review and let me know if any further adjustments are needed.
- Fixes # (#1251 )
- Before
it was not looking good and not matching with the theme of the …
=> redesigned About us page

Feedback.html
---
labels: ''
assignees: ''
---
Changed the text color of navbar icons on the feedback page to make them visible in dark mode.
- Fixes #1252
=> Fixed Navbar buttons visibility in feedback page

features.html
issue number #1270 
I have redesigned the features page as per the theme of the website.
here is an attached video for the same.
https://github.com/user-attachments/assets/6d321a88-5f5c-4679-b21f-7b6e5977d615
=> Features page
