package-lock.json, package.json, postcss.config.js, src/input.css, tailwind.config.js, user.html
This PR adds Tailwind CSS to our project, providing a utility-first CSS framework that will help us build custom designs quickly and consistently.
1. Installed Tailwind CSS and its peer dependencies (postcss, autoprefixer).
2. Added `tailwind.config.js` and `postcss.config.js` configuration files.
3. Created a base CSS file with Tailwind directives.
4. Updated build scripts in `package.json` to compile Tailwind CSS.
5. Added generated Tailwind CSS output file to `.gitignore`.
1. **Writing CSS**: Instead of writing custom CSS, use Tailwind's utility classes in your HTML. For example:
```html
<div class="p-4 m-2 bg-blue-500 text-white rounded-lg shadow-md">
This is a blue box with white text
</div>
```
2. **Building CSS**: 
- For development: Run `npm run dev:css` to start the Tailwind CLI …
=> Fixes #33 Initialized tailwindcss

src/css/login.css
Related Issues: #67 
This PR resolves a UI bug where the 'Sign Up' button was overlapping with the border on the login page. The issue was caused by improper alignment of elements in the layout. The following changes were made to fix the bug:
Adjusted the margin and padding of the button to prevent overlap.
Updated CSS to ensure consistent spacing between elements on different screen sizes.
Tested the fix on various devices to ensure responsiveness and proper alignment.
After fix:
=> Fixed [Bug] #67: 'Sign Up' Button Overlaps with Border on Login Page 

index.html
=> [FIX] Footer updated

index.html, login.html, login.js, src/css/login.css
solved all the problems highlighted in issue #274
=> issue #274 solved✨

Feedback.html, contact.html, features.html, index.html
#348
home page
feature page 
contact page
feedback page
=> ADDED back to top button on all the respective footers

team.html
solved #418 
Now team page footer
resemble to other page 
earlier it was
=> Fix the team.html footer now it looks similar to rest of the pages

login.html
Fix #435 
I have added an password strength meter which enhances user experience.
Before
After
=> added password strength meter

index.html
solved #412 
i have created a faq popup form. I hope you like the design and added it to footer
demo video
https://github.com/user-attachments/assets/233156bf-06a2-43c1-87a2-bee1f4ad80de
=> Created FAQ popup model and added it to footer

.github/workflows/PR_message.yml, .github/workflows/bot.yml
#325 Resolved
This ensures that the contributor requests a PR from the new branch not the main or master branch.
=> Enforce Push to Newly Created Branches, Not Main Branch 

index.html
- Fixes #490 
https://github.com/user-attachments/assets/ec47571e-1f1a-481b-aaac-af6f45ac843b
=> [FIX] Home 404 & logo hover fixed

Feedback.html, contact.html, features.html, index.html, team.html
- Fixes #525 
https://github.com/user-attachments/assets/3153dee1-e3b6-4a79-bfa0-3611570685a6
https://github.com/user-attachments/assets/810676e7-82a1-4aad-ba5f-f804875f49cb
=> [FIX] Social Icon Jittering Fix on Every Page

index.html
This PR Fixes Issue #464 
Previously the scroll up button was fixated at the bottom of the page but now it is made floating at the bottom right corner of the screen.
Before
After
don't forget to label it as GSSOC extd, hacktoberfest accepted with level1/2/3 accordingly.
Thank You!
=> FIXES ISSUE ##464: [Bug]: Scroll up button fixed at the bottom of the screen

index.html
I made improvements to the layout and styling of the index.html file to enhance readability and visibility:
1. Spacing Adjustment: Added spacing in front of the "Welcome to the Ambulance Monitoring System" line to provide better visual structure and make the header stand out.
2. Footer Improvements: Adjusted the display in the footer section to improve its appearance and alignment. Additionally, I added more space to the contact links, making them more prominent and easier to read for better overall visibility.
These changes improve the user interface by enhancing the spacing and structure of key elements, contributing to a cleaner and more user-friendly design.
@mansiruhil13
=> Improved CSS styling and fixed layout issues in index.html

Feedback.html
fixed the top to up scroll button which was not working and added missing faq popup modal at footer, header is also corrected.
issue #521
=> Done fixes in feedback

privacy.html
**BEFORE:--**
**AFTER:--**
this fixes #708
=> updated privacy.html break layout

features.html
The navbar of feature section on the website is experiencing an issue where the content is overlaying it, making it difficult for users to navigate. Additionally, there is unnecessary code written above the navbar, which contributes to the clutter and disrupts the layout. This needs to be addressed to ensure the navbar is fully visible and functional.
Before:
After:
=> Navbar Fixing on Features page

chatbot.html
Now the user can easily differentiate between their message and bot message.
=> Chatbot enhance

index.html
=> [FIX] FAQ Section Glitches Fixed

Feedback.html
Fixed hover issue on feedback page in quick links and contact info section
=> Issue # 885 fixed hover issue on feedback page in quick links and contact info section

sitemap.html
- Fixes #898 
- Nav bar is fixed.
- Nav elements made smaller.
- Body background color fixed.
- Now, texts are visible.
- Links are added to the hover effect to highlight.
=> [FIX] Site Map Page Fixed

responsive.css
- Fixes #913 
- Menu dropdown Button Should be open for smaller screens. not for all screens.
---
=> [FIX] Menu Drop Down fixed for Bigger Screens

index.html, style1.css
=>  Footer is Not Responsive on Different Screen Sizes

contact.html, index.html, team.html
---
title: feat: email format validation while subscribing to newsletter
When the form is submitted, the JavaScript checks if the entered email matches the valid format using a regular expression.
If valid, a notification appears with the message "Thank you for subscribing to our newsletter!" and disappears after 3 seconds.
The form is reset to clear the email input field.
- Fixes #1027 
https://github.com/user-attachments/assets/7224c558-8309-4a6c-a2aa-e943673c9164
- [X ] Bug fix (non-breaking change which fixes an issue)
- [ X] New feature (non-breaking change which adds functionality)
- [X ] I have read the contributing document.
- [ X] I have performed a self-review of my own code.
- [ X] I have commented my code, particularly in hard-to-understand areas.
- [ X] I have added necessary …
=> Email validation checker while subscribing

privacy.html
The privacy page was directly touching the footer section, causing a lack of space between the two elements. This resulted in a crowded layout and poor readability.
To resolve the issue, I have added a bottom margin to the privacy page, ensuring there is sufficient space between the page content and the footer. This improves the visual structure and enhances readability.
- Added CSS margin to the bottom of the privacy page.
- Verified the changes to ensure proper spacing across different screen sizes.
-  Everything is up-to-date and functioning as expected.
This PR resolves the issue and maintains a consistent, user-friendly layout.
=>  Some Changes in privacy.html file

index.html, login.js
---
labels: ''
assignees: ''
---
Key Enhancements:
Performance: Cached passwordField, strengthWeak, strengthMedium, and strengthStrong to avoid repeated DOM lookups.
Dynamic Feedback: Added a displayStrengthMessage function that shows a message (e.g., "Weak password") with corresponding color feedback.
Accessibility: Added aria-label to the password toggle for better screen reader support.
Regex Optimization: Used test() method instead of match() for a more efficient way to check password criteria.
This approach improves the user experience, enhances readability, and makes the code more maintainable.
- Fixes #958
---
=> Corrected Login page and modified password

README.md
---
title: '[Feat] '
labels: ''
assignees: ''
---
Update README for Navigable Table of Contents
Updated README for navigable table of contents. Before it was difficult to navigate to various parts of README section, after addition of table of contents it became easier for navigation.
- Fixes # 1115
---
=> updated README for navigable table of contents

index.html, profile.html, profileedit.html, testp.js
Hello, PR
Add Edit Profile Feature in Profile Page done - #1197
https://github.com/user-attachments/assets/11b76812-9db9-4ab5-8350-330f043bcf00
=> Add Edit Profile Feature in Profile Page done ! #1197 🟢🌟

contact.html, index.html
---
title: 'add dark mode styling to elements present in page '
labels: ''
assignees: ''
---
I have added dark mode styling to elements present inside home and contact us page as currently the dark mode styling mostly changes the bg of site and nothing else in appearance
- Fixes #1209 
https://github.com/user-attachments/assets/7dc4ddd6-af1f-4e24-bc81-28d2975d07be
---
=> adding dark mode styling to elements of home and contact page

contributors/contributors.js
---
labels: ''
assignees: ''
---
Before
After
https://github.com/user-attachments/assets/89031754-4372-41d8-b0db-3a4255ffc6fe
---
=> Added all the contributors

Contactus.html, Feedback.html, SOS.html, about.html, contact.html, homepage.html, team.html
---
about: Use this template for creating pull requests
title: '[FIX] Social media links now open in a new tab'
labels: 'bug, enhancement'
assignees: 'RaviChoudhary'
---
- This pull request addresses an issue where social media links on the site were not opening in a new tab, causing users to navigate away from the main site unintentionally.
- The bug was fixed by adding `target="_blank"` to each social media link, ensuring that they now open in a new browser tab or window. This improves user experience by allowing users to access external social media pages without leaving the main site.
- Fixes #1033 
- This pull request fixes the bug where social media links didn't open in a new tab. I resolved this by adding `target="_blank"` to each link.
=> Fixed the issue of social media links opening in the same tab

about.html, up.html
---
labels: ''
assignees: ''
---
successfully fixed the linking issue of signup button in about page
- Fixes # (#1254 )
*Before*
*After*
---N?A
=> Fixed Signup page in about page

about.html
---
I have successfully implemented a **scroll button** on the **About page** to improve user experience and accessibility. 🚀  
🔹 **Purpose & Benefits:**  
- The About page often contains **detailed information** about the platform, and scrolling manually can be tedious for users.  
- This **scroll button** provides an **instant way to navigate back to the top**, ensuring seamless access to key sections.  
- Enhances the **overall UI/UX** by improving **usability, accessibility, and navigation efficiency**.  
🔹 **Implementation Highlights:**  
- Used **HTML, CSS, and JavaScript** to create the button.  
- Designed a **fixed-position floating button** that appears when users scroll down.  
- Added a **smooth scrolling effect** to ensure a **fluid transition** to the top.  
- Optimized the …
=> 🔹 Added a Scroll Button to the About Page for Enhanced Navigation
